import sys
import os
import re

sys.stdout.reconfigure(encoding='utf-8')

BASE_DIR = r"e:\backup_ext_hdd\android-projects-2026-07-30\Shrinkpdf\app-host\src\main\res"

# Dictionary of strings: key -> { locale -> translation }
TRANSLATIONS = {
    "action_redo": {
        "values": "Redo",
        "values-ar": "إعادة",
        "values-de": "Wiederholen",
        "values-es": "Rehacer",
        "values-fr": "Rétablir",
        "values-hi": "फिर से करें",
        "values-in": "Ulangi",
        "values-it": "Ripeti",
        "values-ja": "やり直し",
        "values-ko": "다시 실행",
        "values-nl": "Opnieuw uitvoeren",
        "values-pl": "Ponów",
        "values-pt": "Refazer",
        "values-pt-rBR": "Refazer",
        "values-ro": "Refă",
        "values-ru": "Повторить",
        "values-th": "ทำซ้ำ",
        "values-tr": "Yinele",
        "values-vi": "Làm lại",
        "values-zh-rCN": "重做",
        "values-zh-rTW": "重做",
    },
    "action_reset": {
        "values": "Reset",
        "values-ar": "إعادة تعيين",
        "values-de": "Zurücksetzen",
        "values-es": "Restablecer",
        "values-fr": "Réinitialiser",
        "values-hi": "रीसेट करें",
        "values-in": "Reset",
        "values-it": "Ripristina",
        "values-ja": "リセット",
        "values-ko": "재설정",
        "values-nl": "Resetten",
        "values-pl": "Resetuj",
        "values-pt": "Redefinir",
        "values-pt-rBR": "Redefinir",
        "values-ro": "Resetează",
        "values-ru": "Сбросить",
        "values-th": "รีเซ็ต",
        "values-tr": "Sıfırla",
        "values-vi": "Đặt lại",
        "values-zh-rCN": "重置",
        "values-zh-rTW": "重設",
    },
    "action_reverse": {
        "values": "Reverse",
        "values-ar": "عكس الترتيب",
        "values-de": "Umkehren",
        "values-es": "Invertir",
        "values-fr": "Inverser",
        "values-hi": "उल्टा करें",
        "values-in": "Balikkan",
        "values-it": "Inverti",
        "values-ja": "反転",
        "values-ko": "순서 뒤집기",
        "values-nl": "Omkeren",
        "values-pl": "Odwróć",
        "values-pt": "Inverter",
        "values-pt-rBR": "Inverter",
        "values-ro": "Inversează",
        "values-ru": "Обратный порядок",
        "values-th": "ย้อนกลับลำดับ",
        "values-tr": "Tersine Çevir",
        "values-vi": "Đảo ngược",
        "values-zh-rCN": "反转顺序",
        "values-zh-rTW": "反轉順序",
    },
    "action_rotate_all": {
        "values": "Rotate All",
        "values-ar": "تدوير الكل",
        "values-de": "Alle drehen",
        "values-es": "Girar todo",
        "values-fr": "Faire pivoter tout",
        "values-hi": "सभी घुमाएँ",
        "values-in": "Putar Semua",
        "values-it": "Ruota tutto",
        "values-ja": "すべて回転",
        "values-ko": "모두 회전",
        "values-nl": "Alles draaien",
        "values-pl": "Obróć wszystko",
        "values-pt": "Girar Tudo",
        "values-pt-rBR": "Girar Tudo",
        "values-ro": "Rotește tot",
        "values-ru": "Повернуть все",
        "values-th": "หมุนทั้งหมด",
        "values-tr": "Tümünü Döndür",
        "values-vi": "Xoay tất cả",
        "values-zh-rCN": "旋转全部",
        "values-zh-rTW": "旋轉全部",
    },
    "label_preview_unavailable": {
        "values": "Preview unavailable",
        "values-ar": "المعاينة غير متوفرة",
        "values-de": "Vorschau nicht verfügbar",
        "values-es": "Vista previa no disponible",
        "values-fr": "Aperçu non disponible",
        "values-hi": "पूर्वावलोकन अनुपलब्ध",
        "values-in": "Pratinjau tidak tersedia",
        "values-it": "Anteprima non disponibile",
        "values-ja": "プレビューを利用できません",
        "values-ko": "미리보기를 사용할 수 없음",
        "values-nl": "Voorbeeld niet beschikbaar",
        "values-pl": "Podgląd niedostępny",
        "values-pt": "Pré-visualização indisponível",
        "values-pt-rBR": "Pré-visualização indisponível",
        "values-ro": "Previzualizare indisponibilă",
        "values-ru": "Предпросмотр недоступен",
        "values-th": "ไม่สามารถแสดงตัวอย่างได้",
        "values-tr": "Önizleme kullanılamıyor",
        "values-vi": "Không có bản xem trước",
        "values-zh-rCN": "预览不可用",
        "values-zh-rTW": "預覽無法使用",
    },
    "dialog_unsaved_title": {
        "values": "Unsaved Changes",
        "values-ar": "تغييرات غير محفوظة",
        "values-de": "Ungespeicherte Änderungen",
        "values-es": "Cambios sin guardar",
        "values-fr": "Modifications non enregistrées",
        "values-hi": "बिना सहेजे गए परिवर्तन",
        "values-in": "Perubahan Belum Disimpan",
        "values-it": "Modifiche non salvate",
        "values-ja": "未保存の変更",
        "values-ko": "저장되지 않은 변경 사항",
        "values-nl": "Niet-opgeslagen wijzigingen",
        "values-pl": "Niezapisane zmiany",
        "values-pt": "Alterações Não Salvas",
        "values-pt-rBR": "Alterações Não Salvas",
        "values-ro": "Modificări nesalvate",
        "values-ru": "Несохранённые изменения",
        "values-th": "การเปลี่ยนแปลงที่ยังไม่ได้บันทึก",
        "values-tr": "Kaydedilmemiş Değişiklikler",
        "values-vi": "Thay đổi chưa lưu",
        "values-zh-rCN": "未保存的更改",
        "values-zh-rTW": "未儲存的變更",
    },
    "dialog_unsaved_message": {
        "values": "You have unsaved changes. Do you want to save or discard them before leaving?",
        "values-ar": "لديك تغييرات غير محفوظة. هل ترغب في حفظها أو تجاهلها قبل المغادرة؟",
        "values-de": "Sie haben ungespeicherte Änderungen. Möchten Sie diese vor dem Verlassen speichern oder verwerfen?",
        "values-es": "Tiene cambios sin guardar. ¿Desea guardarlos o descartarlos antes de salir?",
        "values-fr": "Vous avez des modifications non enregistrées. Voulez-vous les enregistrer ou les abandonner avant de quitter\\?",
        "values-hi": "आपके पास बिना सहेजे गए परिवर्तन हैं। क्या आप छोड़ने से पहले उन्हें सहेजना या छोड़ना चाहते हैं?",
        "values-in": "Anda memiliki perubahan yang belum disimpan. Apakah Anda ingin menyimpan atau membuangnya sebelum keluar?",
        "values-it": "Ci sono modifiche non salvate. Vuoi salvarle o scartarle prima di uscire\\?",
        "values-ja": "未保存の変更があります。移動する前に保存しますか、それとも破棄しますか？",
        "values-ko": "저장되지 않은 변경 사항이 있습니다. 나가기 전에 저장하시겠습니까, 아니면 취소하시겠습니까?",
        "values-nl": "U hebt niet-opgeslagen wijzigingen. Wilt u deze opslaan of verwijderen voordat u weggaat?",
        "values-pl": "Masz niezapisane zmiany. Czy chcesz je zapisać lub odrzucić przed wyjściem?",
        "values-pt": "Você tem alterações não salvas. Deseja salvá-las ou descartá-las antes de sair?",
        "values-pt-rBR": "Você tem alterações não salvas. Deseja salvá-las ou descartá-las antes de sair?",
        "values-ro": "Aveți modificări nesalvate. Doriți să le salvați sau să renunțați înainte de a părăsi pagina?",
        "values-ru": "У вас есть несохранённые изменения. Сохранить или отменить их перед выходом?",
        "values-th": "คุณมีการเปลี่ยนแปลงที่ยังไม่ได้บันทึก ต้องการบันทึกหรือยกเลิกก่อนออกหรือไม่?",
        "values-tr": "Kaydedilmemiş değişiklikleriniz var. Ayrılmadan önce bunları kaydetmek mi yoksa silmek mi istersiniz?",
        "values-vi": "Bạn có thay đổi chưa lưu. Bạn có muốn lưu hoặc hủy chúng trước khi thoát không?",
        "values-zh-rCN": "您有未保存的更改。退出前是否保存或放弃？",
        "values-zh-rTW": "您有未儲存的變更。離開前是否要儲存或放棄？",
    },
    "dialog_unsaved_save": {
        "values": "Save / Export",
        "values-ar": "حفظ / تصدير",
        "values-de": "Speichern / Exportieren",
        "values-es": "Guardar / Exportar",
        "values-fr": "Enregistrer / Exporter",
        "values-hi": "सहेजें / निर्यात करें",
        "values-in": "Simpan / Ekspor",
        "values-it": "Salva / Esporta",
        "values-ja": "保存 / エクスポート",
        "values-ko": "저장 / 내보내기",
        "values-nl": "Opslaan / Exporteren",
        "values-pl": "Zapisz / Eksportuj",
        "values-pt": "Salvar / Exportar",
        "values-pt-rBR": "Salvar / Exportar",
        "values-ro": "Salvează / Exportă",
        "values-ru": "Сохранить / Экспорт",
        "values-th": "บันทึก / ส่งออก",
        "values-tr": "Kaydet / Dışa Aktar",
        "values-vi": "Lưu / Xuất",
        "values-zh-rCN": "保存 / 导出",
        "values-zh-rTW": "儲存 / 匯出",
    },
    "dialog_unsaved_discard": {
        "values": "Discard",
        "values-ar": "تجاهل",
        "values-de": "Verwerfen",
        "values-es": "Descartar",
        "values-fr": "Abandonner",
        "values-hi": "खारिज करें",
        "values-in": "Buang",
        "values-it": "Scarta",
        "values-ja": "破棄",
        "values-ko": "삭제",
        "values-nl": "Verwijderen",
        "values-pl": "Odrzuć",
        "values-pt": "Descartar",
        "values-pt-rBR": "Descartar",
        "values-ro": "Renunță",
        "values-ru": "Сбросить",
        "values-th": "ทิ้ง",
        "values-tr": "Sil",
        "values-vi": "Hủy bỏ",
        "values-zh-rCN": "放弃",
        "values-zh-rTW": "捨棄",
    },
    "dialog_unsaved_continue": {
        "values": "Continue Editing",
        "values-ar": "متابعة التحرير",
        "values-de": "Weiter bearbeiten",
        "values-es": "Continuar editando",
        "values-fr": "Continuer l\\'édition",
        "values-hi": "संपादन जारी रखें",
        "values-in": "Lanjutkan Mengedit",
        "values-it": "Continua a modificare",
        "values-ja": "編集を続ける",
        "values-ko": "편집 계속",
        "values-nl": "Doorgaan met bewerken",
        "values-pl": "Kontynuuj edycję",
        "values-pt": "Continuar Editando",
        "values-pt-rBR": "Continuar Editando",
        "values-ro": "Continuă editarea",
        "values-ru": "Продолжить редактирование",
        "values-th": "แก้ไขต่อ",
        "values-tr": "Düzenlemeye Devam Et",
        "values-vi": "Tiếp tục chỉnh sửa",
        "values-zh-rCN": "继续编辑",
        "values-zh-rTW": "繼續編輯",
    },
    "vanguard_damaged_title": {
        "values": "Damaged PDF",
        "values-ar": "ملف PDF تالف",
        "values-de": "Beschädigte PDF",
        "values-es": "PDF dañado",
        "values-fr": "PDF endommagé",
        "values-hi": "क्षतिग्रस्त PDF",
        "values-in": "PDF Rusak",
        "values-it": "PDF danneggiato",
        "values-ja": "破損したPDF",
        "values-ko": "손상된 PDF",
        "values-nl": "Beschadigde PDF",
        "values-pl": "Uszkodzony plik PDF",
        "values-pt": "PDF Danificado",
        "values-pt-rBR": "PDF Danificado",
        "values-ro": "PDF deteriorat",
        "values-ru": "Повреждённый PDF",
        "values-th": "PDF เสียหาย",
        "values-tr": "Hasarlı PDF",
        "values-vi": "PDF bị hỏng",
        "values-zh-rCN": "损坏的 PDF",
        "values-zh-rTW": "損毀的 PDF",
    },
    "vanguard_damaged_message": {
        "values": "This PDF appears to be damaged or truncated and could not be read safely. Try running Repair or selecting another copy.",
        "values-ar": "يبدو أن ملف PDF هذا تالف أو غير مكتمل ولا يمكن قراءته بأمان. حاول تشغيل أداة الإصلاح أو تحديد نسخة أخرى.",
        "values-de": "Diese PDF scheint beschädigt oder unvollständig zu sein und konnte nicht sicher gelesen werden. Versuchen Sie es mit Reparieren oder wählen Sie eine andere Kopie.",
        "values-es": "Este PDF parece estar dañado o incompleto y no se pudo leer de forma segura. Intente ejecutar Reparar o seleccione otra copia.",
        "values-fr": "Ce PDF semble endommagé ou tronqué et n\\'a pas pu être lu en toute sécurité. Essayez d\\'exécuter la réparation ou sélectionnez une autre copie.",
        "values-hi": "यह PDF क्षतिग्रस्त या अधूरा प्रतीत होता है और इसे सुरक्षित रूप से नहीं पढ़ा जा सका। मरम्मत चलाने का प्रयास करें या कोई अन्य प्रति चुनें।",
        "values-in": "PDF ini tampaknya rusak atau terpotong dan tidak dapat dibaca dengan aman. Coba jalankan Perbaikan atau pilih salinan lain.",
        "values-it": "Questo PDF sembra essere danneggiato o incompleto e non è stato possibile leggerlo in modo sicuro. Prova a eseguire Ripara o seleziona un\\'altra copia.",
        "values-ja": "このPDFは破損しているか不完全なため安全に読み取れませんでした。修復を実行するか別のコピーを選択してください。",
        "values-ko": "이 PDF는 손상되었거나 불완전하여 안전하게 읽을 수 없습니다. 복구를 실행하거나 다른 사본을 선택해 보세요.",
        "values-nl": "Deze PDF lijkt beschadigd of afgekapt en kon niet veilig worden gelezen. Probeer Repareren uit te voeren of kies een andere kopie.",
        "values-pl": "Ten plik PDF wydaje się uszkodzony lub obcięty i nie można go bezpiecznie odczytać. Spróbuj uruchomić Napraw lub wybierz inną kopię.",
        "values-pt": "Este PDF parece estar danificado ou corrompido e não pôde ser lido com segurança. Tente executar a Reparação ou selecione outra cópia.",
        "values-pt-rBR": "Este PDF parece estar danificado ou corrompido e não pôde ser lido com segurança. Tente executar a Reparação ou selecione outra cópia.",
        "values-ro": "Acest PDF pare deteriorat sau trunchiat și nu a putut fi citit în siguranță. Încercați Reparare sau alegeți o altă copie.",
        "values-ru": "Этот PDF повреждён или обрезан и не может быть безопасно прочитан. Попробуйте выполнить восстановление или выберите другой файл.",
        "values-th": "PDF นี้ดูเหมือนจะเสียหายหรือไม่สมบูรณ์และไม่สามารถอ่านได้อย่างปลอดภัย ลองเรียกใช้การซ่อมแซมหรือเลือกสำเนาอื่น",
        "values-tr": "Bu PDF hasarlı veya eksik görünüyor ve güvenli bir şekilde okunamadı. Onar seçeneğini çalıştırmayı veya başka bir kopya seçmeyi deneyin.",
        "values-vi": "Tệp PDF này có vẻ bị hỏng hoặc không đầy đủ và không thể đọc an toàn. Hãy thử chạy Sửa chữa hoặc chọn bản sao khác.",
        "values-zh-rCN": "此 PDF 似乎已损坏或不完整，无法安全读取。请尝试运行修复或选择其他副本。",
        "values-zh-rTW": "此 PDF 似乎已損毀或不完整，無法安全讀取。請嘗試執行修復或選取其他複本。",
    },
    "vanguard_provider_error_title": {
        "values": "File Inaccessible",
        "values-ar": "تعذر الوصول إلى الملف",
        "values-de": "Datei nicht zugänglich",
        "values-es": "Archivo inaccesible",
        "values-fr": "Fichier inaccessible",
        "values-hi": "फ़ाइल अप्राप्य",
        "values-in": "File Tidak Dapat Diakses",
        "values-it": "File inaccessibile",
        "values-ja": "ファイルにアクセスできません",
        "values-ko": "파일에 액세스할 수 없음",
        "values-nl": "Bestand niet toegankelijk",
        "values-pl": "Plik niedostępny",
        "values-pt": "Arquivo Inacessível",
        "values-pt-rBR": "Arquivo Inacessível",
        "values-ro": "Fișier inaccesibil",
        "values-ru": "Файл недоступен",
        "values-th": "ไม่สามารถเข้าถึงไฟล์ได้",
        "values-tr": "Dosyaya Erişilemiyor",
        "values-vi": "Không thể truy cập tệp",
        "values-zh-rCN": "文件无法访问",
        "values-zh-rTW": "檔案無法存取",
    },
    "vanguard_provider_error_message": {
        "values": "The selected file could not be accessed. The storage provider may be unavailable or permissions were revoked.",
        "values-ar": "تعذر الوصول إلى الملف المحدد. قد يكون موفر التخزين غير متوفر أو تم إلغاء الأذونات.",
        "values-de": "Auf die ausgewählte Datei konnte nicht zugegriffen werden. Der Speicheranbieter ist möglicherweise nicht verfügbar oder Berechtigungen wurden widerrufen.",
        "values-es": "No se pudo acceder al archivo seleccionado. Es posible que el proveedor de almacenamiento no esté disponible o que se hayan revocado los permisos.",
        "values-fr": "Impossible d\\'accéder au fichier sélectionné. Le fournisseur de stockage est peut-être indisponible ou les autorisations ont été révoquées.",
        "values-hi": "चयनित फ़ाइल तक नहीं पहुँचा जा सका। संग्रहण प्रदाता अनुपलब्ध हो सकता है या अनुमतियाँ रद्द कर दी गई हैं।",
        "values-in": "File yang dipilih tidak dapat diakses. Penyedia penyimpanan mungkin tidak tersedia atau izin telah dicabut.",
        "values-it": "Impossibile accedere al file selezionato. Il provider di archiviazione potrebbe non essere disponibile o le autorizzazioni sono state revocate.",
        "values-ja": "選択したファイルにアクセスできませんでした。ストレージプロバイダーが利用できないか、権限が取り消された可能性があります。",
        "values-ko": "선택한 파일에 액세스할 수 없습니다. 저장소 공급자를 사용할 수 없거나 권한이 취소되었을 수 있습니다.",
        "values-nl": "Het geselecteerde bestand kon niet worden geopend. De opslagprovider is mogelijk niet beschikbaar of machtigingen zijn ingetrokken.",
        "values-pl": "Nie można uzyskać dostępu do wybranego pliku. Dostawca pamięci może być niedostępny lub uprawnienia zostały cofnięte.",
        "values-pt": "O arquivo selecionado não pôde ser acessado. O provedor de armazenamento pode estar indisponível ou as permissões foram revogadas.",
        "values-pt-rBR": "O arquivo selecionado não pôde ser acessado. O provedor de armazenamento pode estar indisponível ou as permissões foram revogadas.",
        "values-ro": "Fișierul selectat nu a putut fi accesat. Furnizorul de stocare poate fi indisponibil sau permisiunile au fost revocate.",
        "values-ru": "Не удалось получить доступ к выбранному файлу. Хранилище может быть недоступно или разрешения были отозваны.",
        "values-th": "ไม่สามารถเข้าถึงไฟล์ที่เลือกได้ ผู้ให้บริการพื้นที่เก็บข้อมูลอาจไม่พร้อมใช้งานหรือสิทธิ์ถูกเพิกถอน",
        "values-tr": "Seçilen dosyaya erişilemedi. Depolama sağlayıcısı kullanılamıyor olabilir veya izinler iptal edilmiş olabilir.",
        "values-vi": "Không thể truy cập tệp đã chọn. Nhà cung cấp bộ nhớ có thể không khả dụng hoặc quyền đã bị thu hồi.",
        "values-zh-rCN": "无法访问所选文件。存储提供商可能不可用或权限已被撤销。",
        "values-zh-rTW": "無法存取所選檔案。儲存空間提供者可能無法使用或權限已被撤銷。",
    },
    "error_invalid_page_range": {
        "values": "Invalid page range. Please verify the page numbers and try again.",
        "values-ar": "نطاق الصفحات غير صالح. يرجى التحقق من أرقام الصفحات والمحاولة مرة أخرى.",
        "values-de": "Ungültiger Seitenbereich. Bitte überprüfen Sie die Seitenzahlen und versuchen Sie es erneut.",
        "values-es": "Rango de páginas no válido. Verifique los números de página e intente nuevamente.",
        "values-fr": "Plage de pages non valide. Veuillez vérifier les numéros de page et réessayer.",
        "values-hi": "अमान्य पृष्ठ सीमा। कृपया पृष्ठ संख्या सत्यापित करें और पुनः प्रयास करें।",
        "values-in": "Rentang halaman tidak valid. Harap verifikasi nomor halaman dan coba lagi.",
        "values-it": "Intervallo di pagine non valido. Verifica i numeri di pagina e riprova.",
        "values-ja": "無効なページ範囲です。ページ番号を確認してもう一度お試しください。",
        "values-ko": "잘못된 페이지 범위입니다. 페이지 번호를 확인하고 다시 시도하세요.",
        "values-nl": "Ongeldig paginabereik. Controleer de paginanummers en probeer het opnieuw.",
        "values-pl": "Nieprawidłowy zakres stron. Sprawdź numery stron i spróbuj ponownie.",
        "values-pt": "Intervalo de páginas inválido. Verifique os números de página e tente novamente.",
        "values-pt-rBR": "Intervalo de páginas inválido. Verifique os números de página e tente novamente.",
        "values-ro": "Interval de pagini nevalid. Verificați numerele de pagină și încercați din nou.",
        "values-ru": "Недопустимый диапазон страниц. Проверьте номера страниц и повторите попытку.",
        "values-th": "ช่วงหน้าไม่ถูกต้อง โปรดตรวจสอบหมายเลขหน้าและลองอีกครั้ง",
        "values-tr": "Geçersiz sayfa aralığı. Lütfen sayfa numaralarını doğrulayın ve tekrar deneyin.",
        "values-vi": "Phạm vi trang không hợp lệ. Vui lòng kiểm tra lại số trang và thử lại.",
        "values-zh-rCN": "页码范围无效。请核对页码并重试。",
        "values-zh-rTW": "頁碼範圍無效。請核對頁碼後重試。",
    },
    "consent_dialog_decline": {
        "values": "Continue without Personalization",
        "values-ar": "المتابعة بدون تخصيص",
        "values-de": "Ohne Personalisierung fortfahren",
        "values-es": "Continuar sin personalización",
        "values-fr": "Continuer sans personnalisation",
        "values-hi": "निजीकरण के बिना जारी रखें",
        "values-in": "Lanjutkan Tanpa Personalisasi",
        "values-it": "Continua senza personalizzazione",
        "values-ja": "パーソナライズなしで続行",
        "values-ko": "맞춤 설정 없이 계속",
        "values-nl": "Doorgaan zonder personalisatie",
        "values-pl": "Kontynuuj bez personalizacji",
        "values-pt": "Continuar sem Personalização",
        "values-pt-rBR": "Continuar sem Personalização",
        "values-ro": "Continuă fără personalizare",
        "values-ru": "Продолжить без персонализации",
        "values-th": "ดำเนินการต่อโดยไม่ปรับแต่งเฉพาะบุคคล",
        "values-tr": "Kişiselleştirme Olmadan Devam Et",
        "values-vi": "Tiếp tục mà không cá nhân hóa",
        "values-zh-rCN": "不进行个性化设置继续",
        "values-zh-rTW": "不進行個人化設定繼續",
    },
    "generating_previews": {
        "values": "Generating previews…",
        "values-ar": "جارٍ إنشاء المعاينات…",
        "values-de": "Vorschauen werden generiert…",
        "values-es": "Generando vistas previas…",
        "values-fr": "Génération des aperçus…",
        "values-hi": "पूर्वावलोकन तैयार हो रहे हैं…",
        "values-in": "Menghasilkan pratinjau…",
        "values-it": "Generazione anteprime…",
        "values-ja": "プレビューを生成中…",
        "values-ko": "미리보기 생성 중…",
        "values-nl": "Voorbeelden genereren…",
        "values-pl": "Generowanie podglądów…",
        "values-pt": "A gerar pré-visualizações…",
        "values-pt-rBR": "Gerando pré-visualizações…",
        "values-ro": "Se generează previzualizările…",
        "values-ru": "Создание миниатюр…",
        "values-th": "กำลังสร้างภาพตัวอย่าง…",
        "values-tr": "Önizlemeler oluşturuluyor…",
        "values-vi": "Đang tạo bản xem trước…",
        "values-zh-rCN": "正在生成预览…",
        "values-zh-rTW": "正在產生預覽…",
    },
    "label_preview_loading": {
        "values": "Loading…",
        "values-ar": "جارٍ التحميل…",
        "values-de": "Laden…",
        "values-es": "Cargando…",
        "values-fr": "Chargement…",
        "values-hi": "लोड हो रहा है…",
        "values-in": "Memuat…",
        "values-it": "Caricamento…",
        "values-ja": "読み込み中…",
        "values-ko": "로딩 중…",
        "values-nl": "Laden…",
        "values-pl": "Ładowanie…",
        "values-pt": "A carregar…",
        "values-pt-rBR": "Carregando…",
        "values-ro": "Se încarcă…",
        "values-ru": "Загрузка…",
        "values-th": "กำลังโหลด…",
        "values-tr": "Yükleniyor…",
        "values-vi": "Đang tải…",
        "values-zh-rCN": "加载中…",
        "values-zh-rTW": "載入中…",
    },
    "premium_status_loading": {
        "values": "Checking store…",
        "values-ar": "جارٍ التحقق من المتجر…",
        "values-de": "Store wird überprüft…",
        "values-es": "Verificando tienda…",
        "values-fr": "Vérification de la boutique…",
        "values-hi": "स्टोर की जांच हो रही है…",
        "values-in": "Memeriksa toko…",
        "values-it": "Verifica negozio…",
        "values-ja": "ストアを確認中…",
        "values-ko": "스토어 확인 중…",
        "values-nl": "Winkel controleren…",
        "values-pl": "Sprawdzanie sklepu…",
        "values-pt": "A verificar loja…",
        "values-pt-rBR": "Verificando loja…",
        "values-ro": "Se verifică magazinul…",
        "values-ru": "Проверка магазина…",
        "values-th": "กำลังตรวจสอบร้านค้า…",
        "values-tr": "Mağaza kontrol ediliyor…",
        "values-vi": "Đang kiểm tra cửa hàng…",
        "values-zh-rCN": "正在检查商店…",
        "values-zh-rTW": "正在檢查商店…",
    },
    "premium_status_unavailable": {
        "values": "Store unavailable. Tap to retry.",
        "values-ar": "المتجر غير متوفر. انقر لإعادة المحاولة.",
        "values-de": "Store nicht verfügbar. Tippen zum Wiederholen.",
        "values-es": "Tienda no disponible. Toca para reintentar.",
        "values-fr": "Boutique indisponible. Appuyez pour réessayer.",
        "values-hi": "स्टोर अनुपलब्ध है। पुनः प्रयास करने के लिए टैप करें।",
        "values-in": "Toko tidak tersedia. Ketuk untuk mencoba lagi.",
        "values-it": "Negozio non disponibile. Tocca per riprovare.",
        "values-ja": "ストアをご利用いただけません。タップして再試行。",
        "values-ko": "스토어를 사용할 수 없습니다. 다시 시도하려면 탭하세요.",
        "values-nl": "Winkel niet beschikbaar. Tik om opnieuw te proberen.",
        "values-pl": "Sklep niedostępny. Dotknij, aby ponowić.",
        "values-pt": "Loja indisponível. Toque para tentar novamente.",
        "values-pt-rBR": "Loja indisponível. Toque para tentar novamente.",
        "values-ro": "Magazin indisponibil. Atingeți pentru reîncercare.",
        "values-ru": "Магазин недоступен. Нажмите для повтора.",
        "values-th": "ร้านค้าไม่พร้อมใช้งาน แตะเพื่อลองใหม่",
        "values-tr": "Mağaza kullanılamıyor. Yeniden denemek için dokunun.",
        "values-vi": "Cửa hàng không khả dụng. Nhấn để thử lại.",
        "values-zh-rCN": "商店不可用。轻按以重试。",
        "values-zh-rTW": "商店無法使用。輕點以重試。",
    },
    "action_retry": {
        "values": "Retry",
        "values-ar": "إعادة المحاولة",
        "values-de": "Wiederholen",
        "values-es": "Reintentar",
        "values-fr": "Réessayer",
        "values-hi": "पुनः प्रयास करें",
        "values-in": "Coba Lagi",
        "values-it": "Riprova",
        "values-ja": "再試行",
        "values-ko": "다시 시도",
        "values-nl": "Opnieuw proberen",
        "values-pl": "Ponów",
        "values-pt": "Tentar novamente",
        "values-pt-rBR": "Tentar novamente",
        "values-ro": "Reîncearcă",
        "values-ru": "Повторить",
        "values-th": "ลองใหม่",
        "values-tr": "Yeniden Dene",
        "values-vi": "Thử lại",
        "values-zh-rCN": "重试",
        "values-zh-rTW": "重試",
    },
    "redaction_review_title": {
        "values": "Review Redactions",
        "values-ar": "مراجعة التنقيحات",
        "values-de": "Schwärzungen überprüfen",
        "values-es": "Revisar censuras",
        "values-fr": "Vérifier les caviardages",
        "values-hi": "संपादनों की समीक्षा करें",
        "values-in": "Tinjau Redaksi",
        "values-it": "Controlla redazioni",
        "values-ja": "墨消しの確認",
        "values-ko": "수정 사항 검토",
        "values-nl": "Redacties controleren",
        "values-pl": "Przejrzyj zaczernienia",
        "values-pt": "Rever redações",
        "values-pt-rBR": "Revisar redações",
        "values-ro": "Revizuire cenzurări",
        "values-ru": "Проверка скрытых областей",
        "values-th": "ตรวจสอบการเซ็นเซอร์",
        "values-tr": "Sansürleri İncele",
        "values-vi": "Xem lại chỉnh sửa",
        "values-zh-rCN": "审核涂黑",
        "values-zh-rTW": "審查塗黑",
    },
    "redaction_review_message": {
        "values": "%1$d redaction(s) will be permanently applied. Redacted content cannot be recovered.",
        "values-ar": "سيتم تطبيق %1$d تنقيح(ات) بشكل دائم. لا يمكن استرداد المحتوى المنقح.",
        "values-de": "%1$d Schwärzung(en) werden dauerhaft angewendet. Geschwärzte Inhalte können nicht wiederhergestellt werden.",
        "values-es": "Se aplicarán permanentemente %1$d censura(s). El contenido censurado no se puede recuperar.",
        "values-fr": "%1$d caviardage(s) seront appliqués définitivement. Le contenu caviardé ne peut pas être récupéré.",
        "values-hi": "%1$d संपादन स्थायी रूप से लागू किए जाएंगे। संपादित सामग्री को पुनर्प्राप्त नहीं किया जा सकता है।",
        "values-in": "%1$d redaksi akan diterapkan secara permanen. Konten yang disunting tidak dapat dipulihkan.",
        "values-it": "%1$d redazione/i verranno applicate in modo permanente. Il contenuto oscurato non può essere recuperato.",
        "values-ja": "%1$d件の墨消しが完全に適用されます。墨消しされた内容は復元できません。",
        "values-ko": "%1$d개의 수정 사항이 영구적으로 적용됩니다. 수정된 내용은 복구할 수 없습니다.",
        "values-nl": "%1$d redactie(s) worden definitief toegepast. Geredigeerde inhoud kan niet worden hersteld.",
        "values-pl": "%1$d zaczernień zostanie zastosowanych na stałe. Zaczernionej zawartości nie można odzyskać.",
        "values-pt": "%1$d redação(ões) serão aplicadas permanentemente. O conteúdo ocultado não pode ser recuperado.",
        "values-pt-rBR": "%1$d redação(ões) serão aplicadas permanentemente. O conteúdo ocultado não pode ser recuperado.",
        "values-ro": "%1$d cenzurări vor fi aplicate permanent. Conținutul cenzurat nu poate fi recuperat.",
        "values-ru": "Будет навсегда применено скрытий: %1$d. Скрытое содержимое восстановить невозможно.",
        "values-th": "จะใช้การเซ็นเซอร์ %1$d รายการอย่างถาวร เนื้อหาที่ถูกเซ็นเซอร์จะไม่สามารถกู้คืนได้",
        "values-tr": "%1$d sansür kalıcı olarak uygulanacaktır. Sansürlenen içerik geri alınamaz.",
        "values-vi": "%1$d chỉnh sửa sẽ được áp dụng vĩnh viễn. Nội dung đã chỉnh sửa không thể phục hồi.",
        "values-zh-rCN": "将永久应用 %1$d 处涂黑。涂黑的内容将无法恢复。",
        "values-zh-rTW": "將永久套用 %1$d 處塗黑。塗黑的內容將無法復原。",
    },
    "redaction_review_confirm": {
        "values": "Apply Redactions",
        "values-ar": "تطبيق التنقيحات",
        "values-de": "Schwärzungen anwenden",
        "values-es": "Aplicar censuras",
        "values-fr": "Appliquer les caviardages",
        "values-hi": "संपादन लागू करें",
        "values-in": "Terapkan Redaksi",
        "values-it": "Applica redazioni",
        "values-ja": "墨消しを適用",
        "values-ko": "수정 사항 적용",
        "values-nl": "Redacties toepassen",
        "values-pl": "Zastosuj zaczernienia",
        "values-pt": "Aplicar redações",
        "values-pt-rBR": "Aplicar redações",
        "values-ro": "Aplică cenzurările",
        "values-ru": "Применить скрытие",
        "values-th": "ใช้การเซ็นเซอร์",
        "values-tr": "Sansürleri Uygula",
        "values-vi": "Áp dụng chỉnh sửa",
        "values-zh-rCN": "应用涂黑",
        "values-zh-rTW": "套用塗黑",
    }
}

for folder in os.listdir(BASE_DIR):
    if not (folder == "values" or folder.startswith("values-")):
        continue
    file_path = os.path.join(BASE_DIR, folder, "strings.xml")
    if not os.path.isfile(file_path):
        continue

    with open(file_path, "r", encoding="utf-8") as f:
        content = f.read()

    to_add = []
    for key, loc_map in TRANSLATIONS.items():
        if f'name="{key}"' not in content:
            val = loc_map.get(folder, loc_map.get("values", ""))
            to_add.append(f'    <string name="{key}">{val}</string>')

    if to_add:
        addition = "\n" + "\n".join(to_add) + "\n</resources>"
        content = re.sub(r'</resources>\s*$', addition, content)
        with open(file_path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"Updated {folder}/strings.xml with {len(to_add)} strings.")
    else:
        print(f"{folder}/strings.xml already up to date.")
